version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "primefix-web-backend"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Install phase complete"

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - echo "ECR URI is $ECR_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $ECR_URI:$IMAGE_TAG
      
